name: Postman api githubAction test setup by karan

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman and HTML Reporter
        run: npm install -g newman newman-reporter-htmlextra
        
      - name: Ensure Reports folder exists
        run: mkdir -p Reports

      - name: Run Postman Collection
        run: |
          newman run main_collection/E-commerce.postman_collection.json \
          --verbose \
          -r htmlextra \
          --reporter-htmlextra-export Reports/report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: Reports/report.html
